use_frameworks!

target 'ASAlertViewController_Example' do
  pod 'ASAlertViewController', :path => '../'

  target 'ASAlertViewController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
